    <div class="well footer">
    <img src="img/divider.png" class="divider-footer"><br>
    The Hoghton Players is a Registered Charity no. <a href="http://apps.charitycommission.gov.uk/Showcharity/RegisterOfCharities/CharityWithoutPartB.aspx?RegisteredCharityNumber=1006287&SubsidiaryNumber=0">1006287</a><br>
    Affiliated to <a href="https://www.noda.org.uk">NODA</a><br>
    Wesite design by <a href="#">Xarkos</a>
    </div>