<div class="navbar-inverse navbar-default navbar-fixed-top nav-background" role="navigation">
        
     <div class="container">

         <a class="navbar-brand" href="#">The Hoghton Players - Members Area</a>
      
     
         <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>

         <div class="collapse navbar-collapse navHeaderCollapse inverse">
                <ul class="nav navbar-nav navbar-right highlight">
                    <li><a href="index.php">Notice Board</a></li>
                    <li><a href="history.php">Library</a></li>
                    <li><a href="login.php">Log out</a></li>
                </ul>
          </div>

    </div>

</div>