<div class="navbar navbar-default navbar-fixed-top nav-background" role="navigation">
        
     <div class="container">

         <a class="navbar-brand" href="#">The Hoghton Players</a>
      
     
         <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>

         <div class="collapse navbar-collapse navHeaderCollapse inverse">
                <ul class="nav navbar-nav navbar-right highlight">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="history.php">History</a></li>
                    <li class="dropdown">
                    <a href="index.php" class="dropdown-toggle" data-toggle="dropdown">Past Productions<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="piratesofpenzance2014.php">2014 - The Pirates of Penzance</a><li>
                        <li><a href="yeomanoftheguard2013.php">2013 -The Yeoman of the Guard</a></li>
                        <li><a href="patience2012.php">2012 - Patience</a></li>
                        <li><a href="mikado2011.php">2011 - The Mikado</a><li>
                        <li><a href="hmspinafore2010.php">2010 - HMS Pinafore</a></li>
                        <li><a href="ruddigore2009.php">2009 - Ruddigore</a></li>
                        <li><a href="gondoliers2008.php">2008 - The Gondoliers</a><li>
                        <li><a href="iolanthe2007.php">2007 - Iolanthe</a></li>
                        <li><a href="marathon2006.php">2006 - Marathon</a></li>
                        <li><a href="yeomanoftheguard2006.php">2006 - The Yeoman of the Guard</a></li>
                        <li><a href="sorcerer2005.php">2005 - The Sorerer</a></li>
                        <li><a href="mikado2004.php">2004 - The Mikado</a></li>
                        <li><a href="thezoo2003.php">2003 - The Zoo</a></li>
                        <li><a href="hmspinafore2003.php">2003 - HMS Pinafore</a></li>
                        <li><a href="piratesofpenzance2002.php">2002 - The Pirates of Penzance</a></li>
                        <li><a href="patience2001.php">2001 - Patience</a></li>
                        <li><a href="1952to2000productions.php">1952 to 2000 Productions</a></li>
                        <li><a href="https://picasaweb.google.com/104029567305161715606/IndividualPics?feat=directlink">Other Pictures (Picassa)</a></li>
                    </ul>
                    </li>     
                    <li><a href="chairman.php">Chairman's Address</a></li>
                     <li><a href="irisaughton.php">The Iris Aughton Bursary</a></li>
                 
                    <li><a href="login.php">Log in</a></li>
                </ul>
          </div>

    </div>

</div>