<img src="img/gands.jpg" class="gands img-responsive">
<img src="img/divider.png" class="divider-rightcolumn img-responsive"><br>

<div class="addthis_sharing_toolbox"></div>

<h5>Join The Hoghton Players</h5>
<div style="text-align:justify;">
    We are always looking out for new members, why not contact us now for more information...
</div>
<br>
<h5>Join our emailing list</h5>
<div style="text-align:justify;">
    If you like to be advised of forthcoming concerts and shows you can subscribe to our quarterly email by clicking <href="#"> Here </a>.
</div>
<br>
<h5>Join us on Facebook</h5>

<a href="https://www.facebook.com/HoghtonPlayers"><img src="img/facebook.jpg" class="archiveimage responsive"></a>

<br>
<h5>Discover more about Gilbert & Sullivan</h5>
<div style="text-align:justify;">
    You can find more information about the magical world of Gilbert & Sullivan here...<br><br>
</div>

<a href="http://diamond.boisestate.edu/gas/index.html"><img src="img/archive.gif" class="archiveimage responsive"></a>



<img src="img/divider.png" class="divider-rightcolumn img-responsive flipped"><br>